services:
  db:
    image: postgres:15
    container_name: postgres_seche
    restart: always
    environment:
      POSTGRES_DB: calories_tracker
      POSTGRES_USER: cobrasw3
      POSTGRES_PASSWORD: ${DB_PASSWORD} 
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana
    container_name: grafana_seche
    restart: always

    expose:
      - "3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - db

  bot:
    build: .
    container_name: telegram_bot_seche
    restart: always
    depends_on:
      - db
    env_file:
      - .env

  nginx-proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_proxy_seche
    restart: always
    ports:
      - '80:80'   
      - '443:443'
      - '81:81' 
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt

volumes:
  postgres_data:
  grafana_data: